name: innim_l10n
description: Localizations dependency for Innim Team projects.
version: 0.1.0
homepage: https://github.com/innim/
repository: https://github.com/Innim/flutter_innim_l10n
issue_tracker: https://github.com/Innim/flutter_innim_l10n/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  multiple_localization: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
