name: innim_l10n
description: Localizations dependency for Innim Team projects.
version: 0.2.1
homepage: https://github.com/innim/
repository: https://github.com/Innim/flutter_innim_l10n
issue_tracker: https://github.com/Innim/flutter_innim_l10n/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  multiple_localization: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
